name: build-release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r config/requirements.txt pyinstaller
      - name: Build binary
        run: |
          pyinstaller --onefile -n vaultsh src/main.py
      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: vaultsh-${{ matrix.os }}
          path: dist/*
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Gather
        run: |
          mkdir upload
          find dist -type f -name 'vaultsh*' -exec bash -c 'cp "$1" "upload/$(basename $1 | tr " " "")-$(echo $GITHUB_REF_NAME)"' _ {} \;
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: upload/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
